# Generated by Django 3.1.3 on 2020-11-06 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='form_org',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('Exercise', models.CharField(max_length=30)),
                ('Meditation', models.CharField(max_length=30)),
                ('Devotion', models.CharField(max_length=30)),
                ('Practice', models.CharField(max_length=30)),
                ('No_junkFood', models.CharField(max_length=30)),
                ('Optimistic', models.CharField(max_length=30)),
                ('Manan', models.CharField(max_length=30)),
                ('Shoka', models.CharField(max_length=30)),
                ('Vyartha', models.CharField(max_length=30)),
                ('Glitch', models.CharField(max_length=30)),
            ],
        ),
    ]
